Merged request
salvimohan/simply_erp pull request #13
Opened 2023-10-26 08:12 UTC by AnushaTandon

2023-10-26 12:01 UTC, ror-mahesh requested changes

2023-10-26 12:01 UTC, ror-mahesh commented on spec/factories/merge_requests.rb
> +
if we not using then remove  it.

2023-10-26 12:01 UTC, ror-mahesh commented on spec/factories/merged_requests.rb
> +
same

2023-10-26 12:01 UTC, ror-mahesh commented on spec/models/merge_request_spec.rb
> +
same

2023-10-26 12:01 UTC, ror-mahesh commented on spec/models/merged_request_spec.rb
> +RSpec.describe MergedRequest, type: :model do
same

2023-10-26 13:39 UTC, AnushaTandon commented on app/controllers/merged_requests_controller.rb
> +  before_action :set_merged_request, only: :update
but i used only update for ajax calling in update action.

2023-10-27 13:31 UTC, ror-mahesh requested changes

2023-10-27 13:31 UTC, ror-mahesh commented on app/controllers/merged_requests_controller.rb
> +  before_action :set_merged_request, only: :update
no,
We are using same query in set_merged_request, edit and destroy.
So why we not use the same filter for all of thease?

2023-10-27 13:31 UTC, ror-mahesh commented on app/controllers/merged_requests_controller.rb
> +    @project = @task.project if @task.present?
which type of error.
I think in your database there are wrong data also present..

2023-10-27 13:31 UTC, ror-mahesh commented on app/views/merged_requests/_form.html.erb
> +      <%= form.select :status, [['Open', 'open'], ['Closed', 'closed'], ['Draft', 'draft'], ['Merged', 'merged']], {}, class: 'form-control', selected: @merged_request.status %>
can we use status as enum.

2023-10-27 13:31 UTC, ror-mahesh commented on app/views/merged_requests/_mr.html.erb
> +      <% @task.merged_requests&.each do |merge_request| %>
is & needed?

2023-10-27 13:31 UTC, ror-mahesh commented on app/views/merged_requests/_mr.html.erb
> +            <% if merge_request&.id&.present? %> <%= link_to 'Edit' , edit_task_merged_request_path(@task, merge_request), class: "btn btn-primary mb-3 right", data: { bs_toggle: "modal",bs_target: "
same.

2023-11-08 08:59 UTC, merged