Logged hours issue
salvimohan/simply_erp pull request #16
Opened 2023-11-06 14:20 UTC by shivamchouhan123

2023-11-07 07:20 UTC, ror-mahesh requested changes

2023-11-07 07:20 UTC, ror-mahesh commented on app/controllers/merged_requests_controller.rb
> +    redirect_to task_logged_hours_url, notice: 'Hour was successfully destroyed.'
notice message wrong.

2023-11-07 07:20 UTC, ror-mahesh commented on app/views/merged_requests/_form.html.erb
> +      <%= form.select :status, [['Open', 'open'], ['Closed', 'closed'], ['Draft', 'draft'], ['Merged', 'merged']], {}, class: 'form-control', selected: @merged_request.status %>
can we use enum for status.

2023-11-07 07:20 UTC, ror-mahesh commented on app/views/merged_requests/_mr.html.erb
> +            <% if merge_request&.id&.present? %> <%= link_to 'Edit' , edit_task_merged_request_path(@task, merge_request), class: "btn btn-primary mb-3 right", data: { bs_toggle: "modal",bs_target: "
no need to use `&` here also why we check MR id here?.

2023-11-07 07:20 UTC, ror-mahesh commented on app/views/merged_requests/create.js.erb
> +	alert("Invalid details");
can we show actual error instead of static message.

2023-11-07 08:06 UTC, shivamchouhan123 commented on app/controllers/merged_requests_controller.rb
> +    redirect_to task_logged_hours_url, notice: 'Hour was successfully destroyed.'
so here can i use Merged Request successfully destroyed.

2023-11-07 12:51 UTC, ror-mahesh requested changes

2023-11-07 12:51 UTC, ror-mahesh commented on app/models/merged_request.rb
> +
remove extra line.

2023-11-07 12:51 UTC, ror-mahesh commented on app/views/merged_requests/_form.html.erb
> +      <%= form.text_field :url_link,  value: "#{@merged_request.url_link}", class: "form-control" %>
why we pass value here,
Rails form already load the value of attributes.

2023-11-08 06:22 UTC, ror-mahesh requested changes

2023-11-08 06:22 UTC, ror-mahesh commented on app/views/tasks/_mr.html.erb
> +         <%= form.time_field :url_link,  value: "#{@logged_hour.total_time}", class: "form-control" %>
here also value passed?

2023-11-08 06:30 UTC, ror-mahesh approved these changes

2023-11-08 08:59 UTC, merged