Ticket_url
salvimohan/simply_erp pull request #9
Opened 2023-10-23 10:55 UTC by AnushaTandon

2023-10-23 11:08 UTC, ror-mahesh requested changes
@AnushaTandon resolve conflict.

2023-10-23 11:08 UTC, ror-mahesh commented on app/models/project.rb
> +      return if end_date.blank? || start_date.blank?
we already validate presence true.

2023-10-23 11:08 UTC, ror-mahesh commented on app/views/tasks/_form.html.erb
> +                                            <%= form.text_field :ticket_url, class: 'form-control' %>
can we also add url validation for ticket_url.

2023-10-23 11:14 UTC, AnushaTandon commented on app/models/project.rb
> +      return if end_date.blank? || start_date.blank?
sir vo is line ke bina error de raha hai.

2023-10-23 11:15 UTC, AnushaTandon commented on app/views/tasks/_form.html.erb
> +                                            <%= form.text_field :ticket_url, class: 'form-control' %>
yes, sir..

2023-10-23 11:35 UTC, ror-mahesh requested changes

2023-10-23 11:35 UTC, ror-mahesh commented on app/models/project.rb
> +      return if end_date.blank? || start_date.blank?
because we didn't add validation of presence  for  start date and end date.

2023-10-23 12:40 UTC, ror-mahesh requested changes
@AnushaTandon Validation is missing for ticket_url,

2023-10-23 12:40 UTC, ror-mahesh commented on app/models/task.rb
> +  validates :start_date, :end_date, presence: true
can we add all this in single line.

2023-10-24 07:22 UTC, ror-mahesh approved these changes

2023-10-24 07:23 UTC, rorshaan approved these changes

2023-10-24 07:24 UTC, merged